apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ml-scheduler.fullname" . }}-config
  labels:
    {{- include "ml-scheduler.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.api.env.NODE_ENV | quote }}
  PORT: {{ .Values.api.env.PORT | quote }}
  LOG_LEVEL: {{ .Values.api.env.LOG_LEVEL | quote }}
  METRICS_ENABLED: "true"
  REDIS_URL: "redis://{{ include "ml-scheduler.redisHost" . }}:6379"
  ML_SERVICE_URL: "http://{{ include "ml-scheduler.fullname" . }}-ml:5000"
